# Generated by Django 4.2.4 on 2023-11-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.IntegerField()),
                ('rasm', models.CharField(max_length=300)),
                ('malumot', models.CharField(blank=True, max_length=30, null=True)),
                ('turi', models.CharField(max_length=30)),
                ('soni', models.IntegerField()),
                ('tg_id', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.IntegerField(unique=True)),
                ('rasm', models.CharField(max_length=300)),
                ('malumot', models.CharField(blank=True, max_length=30, null=True)),
                ('turi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('fam', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
