# Generated by Django 4.2.4 on 2023-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_alter_maxsulotlar_turi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzinka',
            name='narxi',
        ),
        migrations.AlterField(
            model_name='maxsulotlar',
            name='malumot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nomi',
            field=models.CharField(max_length=30),
        ),
    ]
