# Generated by Django 4.2.4 on 2023-11-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_remove_korzinka_narxi_alter_maxsulotlar_malumot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzinka',
            name='date',
        ),
        migrations.RemoveField(
            model_name='korzinka',
            name='status',
        ),
        migrations.RemoveField(
            model_name='korzinka',
            name='tg_id',
        ),
    ]
