# Generated by Django 4.2.4 on 2023-11-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_remove_korzinka_date_remove_korzinka_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Korzinka',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
