# Generated by Django 4.2.4 on 2023-11-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_remove_maxsulotlar_turi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('rasm', models.CharField(max_length=300)),
                ('malumot', models.CharField(blank=True, max_length=30, null=True)),
                ('turi', models.CharField(max_length=30)),
                ('soni', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('fam', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='maxsulotlar',
            name='turi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myfiles.menu'),
            preserve_default=False,
        ),
    ]
