# Generated by Django 4.2.4 on 2023-11-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_korzinka_subscribe_maxsulotlar_turi'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulotlar',
            name='birlik',
            field=models.CharField(choices=[('kg', 'kg'), ('l', 'litr')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
