# Generated by Django 4.2.4 on 2023-11-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_maxsulotlar_birlik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxsulotlar',
            name='birlik',
        ),
    ]
