# Generated by Django 4.2.4 on 2023-11-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_remove_maxsulotlar_birlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulotlar',
            name='turi',
            field=models.CharField(max_length=30),
        ),
    ]
