# Generated by Django 4.2.4 on 2024-01-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_alter_maxsulotlar_turi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxsulotlar',
            old_name='turi',
            new_name='tur',
        ),
    ]
