from aiogram.types import ReplyKeyboardMarkup,KeyboardButton

multik_button = ReplyKeyboardMarkup(
    keyboard =[
        [
            KeyboardButton(text="a")
        ],
        [
            KeyboardButton(text="b")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="")
        ],
        [
            KeyboardButton(text="🔙Orqaga")
        ]
    ])
